config/routes.rb
Runnery::Application.routes.draw do

 resources :users
 resources :sessions, only: [:new, :create, :destroy]
 resources :orders, only: [:create,:destroy,:update]
 resources :locations, only: [:create,:destroy,:update]

 root 'static_pages#home'

 match '/running',  to: 'users#running',  via: 'get'
 match '/done',  to: 'users#done_today',  via: 'get'
 match '/all_done',  to: 'users#all_done',  via: 'get'
 match '/signup',  to: 'users#new',  via: 'get'
 match '/signin',  to: 'sessions#new',         via: 'get'
 match '/signout', to: 'sessions#destroy',     via: 'delete'
 match '/site_info', to: 'static_pages#site_info', via: 'get'
 match '/dropoffs_wait', to: 'static_pages#dropoffs_wait', via: 'get'
 match '/pickups_wait', to: 'static_pages#pickups_wait', via: 'get'
 match '/dropoffs',  to: 'users#dropoffs',  via: 'get'
 match '/pickups',  to: 'users#pickups',  via: 'get'
 match '/dropoffs_done',  to: 'users#dropoffs_done',  via: 'get'
 match '/pickups_done',  to: 'users#pickups_done',  via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :location, dependent: :destroy
  has_many :orders, dependent: :destroy
  

	validates :name, presence: true, length: { maximum: 50 }
	VALID_PHONE_REGEX = /(\d{10})/
	validates :phone, presence: true, format: { with: VALID_PHONE_REGEX }, 
            uniqueness: true, length: { maximum: 10 }
	validates :address, allow_blank: true, uniqueness: true
	has_secure_password
	validates :password, length: { minimum:6 }
  before_create :create_remember_token


  def restaurant_wait
     
     Order.where(:driver_id => nil)
          .where(:user_id => id)
     
  end

  def restaurant_run

     Order.where(:user_id => id)
     .where(:receipt => nil)
     .where("driver_id IS NOT ?", nil) 

  end

  def restaurant_done

     Order.where(:user_id => id)
          .where("receipt IS NOT ?", nil)
          .where("driver_id IS NOT ?", nil)
          .where("DATE(created_at) = DATE(?)", Time.now)
          
  end

  def restaurant_all_done

     Order.where(:user_id => id)
          .where("receipt IS NOT ?", nil)
          .where("driver_id IS NOT ?", nil)

  end


  def driver_wait
    
    lat = Location.where(:user_id => id).pluck(:lat)
    long = Location.where(:user_id => id).pluck(:lng)
    
      Order.where(:driver_id => nil)
           .near([lat.shift, long.shift], 2)
  end

  def driver_run

    Order.where(:receipt => nil)
         .where(:driver_id => id)
  
  end

  def driver_done

    Order.where("receipt IS NOT ?", nil)
         .where(:driver_id => id)
         .where("DATE(created_at) = DATE(?)", Time.now)
   
  end

  def driver_all_done

    Order.where("receipt IS NOT ?", nil)
         .where(:driver_id => id)
   
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user, only: [:index, :destroy]

  def index
    @users = User.paginate(page: params[:page])
    @user = User.find_by(params[:id])
    if !@user.admin = true
      redirect_to root_url
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def running
    @user = User.find_by(params[:id])
    @order  = current_user.orders.build

    if driver?
    @feed_items = current_user.driver_run
    else
    @feed_items = current_user.restaurant_run
    end
    
    @hash = Gmaps4rails.build_markers(@feed_items) do |feed_item, marker|
      
        marker.lat feed_item.latitude
        marker.lng feed_item.longitude
        marker.infowindow render_to_string(partial: '/shared/feed_item',
          collection: @feed_items.select{|feed_items| feed_items.address == feed_item.address})
    end
  end

  def done_today
    @user = User.find_by(params[:id])

    if driver?
      @feed_items = current_user.driver_done.reorder("created_at DESC")
    else
      @feed_items = current_user.restaurant_done.reorder("created_at DESC")
    end

    @hash = Gmaps4rails.build_markers(@feed_items) do |feed_item, marker|
        marker.lat feed_item.latitude
        marker.lng feed_item.longitude
        marker.infowindow render_to_string(partial: '/shared/feed_item',
          collection: @feed_items.select{|feed_items| feed_items.address == feed_item.address})
    end
  end

  def all_done
  @user = User.find_by(params[:id])

   if driver?
    @feed_items = current_user.driver_all_done.reorder("created_at DESC")
   else
    @feed_items = current_user.restaurant_all_done.reorder("created_at DESC")
   end
   
  end

  def pickups
    if signed_in? && driver?
      @user = User.find_by(params[:id])
      @feed_items = current_user.driver_run

        @hash = Gmaps4rails.build_markers(@feed_items) do |feed_item, marker|
      
          marker.lat feed_item.origin_latitude
          marker.lng feed_item.origin_longitude
          marker.infowindow render_to_string(partial: '/shared/feed_item',
          collection: @feed_items.select{|feed_items| feed_items.origin_address == feed_item.origin_address})

        
      end
    end
  end

  def dropoffs
    if signed_in?
      @user = User.find_by(params[:id])
      if driver?
       @feed_items = current_user.driver_run
      else
       @feed_items = current_user.restaurant_run
      end

        @hash = Gmaps4rails.build_markers(@feed_items) do |feed_item, marker|
      
          marker.lat feed_item.latitude
          marker.lng feed_item.longitude
         marker.infowindow render_to_string(partial: '/shared/feed_item',
          collection: @feed_items.select{|feed_items| feed_items.address == feed_item.address})

        
      end
    end
  end

  def dropoffs_done
     @user = User.find_by(params[:id])

    if driver?
      @feed_items = current_user.driver_done.paginate(page: params[:page], :per_page => 3).reorder("created_at DESC")
    else
      @feed_items = current_user.restaurant_done.paginate(page: params[:page], :per_page => 3).reorder("created_at DESC")
    end

    @hash = Gmaps4rails.build_markers(@feed_items) do |feed_item, marker|
        marker.lat feed_item.latitude
        marker.lng feed_item.longitude
        marker.infowindow feed_item.address
    end
  end

  def pickups_done
     @user = User.find_by(params[:id])

    if driver?
      @feed_items = current_user.driver_done.paginate(page: params[:page], :per_page => 3).reorder("created_at DESC")
    else
      @feed_items = current_user.restaurant_done.paginate(page: params[:page], :per_page => 3).reorder("created_at DESC")
    end

    @hash = Gmaps4rails.build_markers(@feed_items) do |feed_item, marker|
        marker.lat feed_item.origin_latitude
        marker.lng feed_item.origin_longitude
        marker.infowindow feed_item.origin_address
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
   @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Runnery!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
     if @user.update_attributes(user_params)
     flash[:success] = "User Register Updated!"
     redirect_to @user
     else
     redirect_to edit_user_path
   end
  end

  def destroy
    @user = User.find(params[:id])
    User.find(params[:id]).destroy
    flash[:error] = "User deleted."
    redirect_to root_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :phone, :address, :user_type, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_gmap_script.mobile.erb
<script type="text/javascript">

    handler = Gmaps.build('Google');
    handler.buildMap
    
    	({ provider: {}, internal: {id: 'map'}}, function(){
   		   markers = handler.addMarkers(<%=raw @hash.to_json %>);
           handler.bounds.extendWith(markers);
           handler.fitMapToBounds();
        });

</script>

app/views/users/_run.html.erb
<%= form_for(current_user.deliveries.build(running_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :running_id %></div>
  <%= f.submit "Run!", class: "btn-small" %>
<% end %>

app/views/users/_run_form.html.erb
<li>
  <% if current_user.running?(@user) %>
    <%= render 'stop_run' %>
  <% else %>
    <%= render 'run' %>
  <% end %>
 </li>

app/views/users/all_done.mobile.erb
<%= render "shared/javascript_headers" %>

<% provide(:title, 'All Done') %>

    <h3 style="font-family: Courier New; font-style:italic; margin-left:0; margin-top:20px; padding:0;"> Done: All (

      <% if driver? %>
      <%= current_user.driver_all_done.count %>
      <% else %>
      <%= current_user.restaurant_all_done.count %>
      <% end %>
      )
    </h3> 

      <h4 style="font-family: Courier New; font-style:italic; margin-left:0;">Go to: <%= link_to ' Done Today', done_path, style: "color:black", rel: :external %></h4>

       <% @feed_items.each do |feed_item| %>
 <div class="container pull-left" style="width:380px; background:rgba(172,228,252,.5);">
  
  <li>
      <li class="dropdown">

        <a href="#" class="dropdown-toggle" 
            data-toggle="dropdown" style="color:black;">

           <% if driver? %>
        <%= feed_item.origin_address %>
        </a>
        <ul class="dropdown-menu">
           <%= feed_item.origin_phone %>

        <% else %>
        <%= feed_item.driver_name %>
        </ul>
        <ul class="dropdown-menu">
           <%= feed_item.driver_phone %>
        <% end %>

        </ul>

      </li>
        


        <li class="dropdown">

        <a href="#" class="dropdown-toggle" 
            data-toggle="dropdown" style="color:black;">

        <%= feed_item.address %>
        </a>
        <ul class="dropdown-menu">
           <%= feed_item.phone %>

        </ul>



      </li>


        <%= time_ago_in_words(feed_item.created_at) %> ago.

    

        </li>
        </div>

        <br>
    <br>
    <br>
    <br>

        <div class:"container pull-left" style="width:380px;">

    <% if !feed_item.redeemed? %>
        <% if driver? %>

        <% if feed_item.receipt? %>

            <%= form_for feed_item do |f| %>
     
               <%= f.hidden_field :redeemed, :value => true %>
               <%= f.submit "Receipt!", 
                      class: "btn-small btn-warning", rel: :external %> 
        <% end %>
        <% end %>
      <% end %>
      <% end %>

  
  <% end %>
   <%= will_paginate @feed_items %>
</div>


  



app/views/users/done_today.html.erb
<script src="//maps.google.com/maps/api/js?key=[your API key]"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<%= render "shared/javascript_headers" %>

<% provide(:title, 'Done Today') %>

  <div  id="map" style="position:absolute; width:100%; height:100%;"></div>


      <%= render 'shared/gmap_script' %>
      
      
       <div style="position:absolute;z-index:1;top:150px;left:100px;width:350px;background: rgba(172,228,252,.9);box-shadow: 10px 10px 5px #888888">
				             
				             <%= render 'shared/feed'%>
				            </div>

app/views/users/done_today.mobile.erb
<%= render "shared/javascript_headers" %>

<% provide(:title, 'Done Today') %>
    
 <div  id="map" style="position:absolute; width:100%; height:100%;"></div>


      <%= render 'shared/gmap_script' %>

app/views/users/edit.mobile.erb
<% provide(:title, 'Edit Register') %>
<h3 style="font-family: Courier New; font-style:italic; margin-left:0; margin-top:20px; padding:0;">Edit Register</h3>

<div style="width:160px;">
<%= form_for(@user) do |f| %>
   
    <%= render 'shared/error_messages', object: f.object %>
  	
    <%= f.label :user_type %>
    <%= f.select :user_type, [["Driver", true],["Restaurant", false]] %>

    <br>
    <br>

  </div>

  <div class="span4" style="margin: 0 0 0 0px;">
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :phone %>
    <%= f.text_field :phone, placeholder: "8885551234" %>

    <% if signed_in? && driver? %>
 
    <%= f.label :address, "Restaurant Address", style: "display:none" %>
    <%= f.text_area :address, placeholder: "Full restaurant address", style: "display:none" %>

    <% elsif signed_in? && !driver? %>

    <%= f.label :address, "Restaurant Address" %>
    <%= f.text_area :address, placeholder: "Full restaurant address" %>

    <% end %>
 
    <%= f.label :password %>
    <%= f.password_field :password, placeholder: "6 char min" %>

    <%= f.label :password_confirmation, "Confirm password" %>
    <%= f.password_field :password_confirmation %>

  <br>
  <br>
  
    <%= f.submit "Edit!", class: "btn-large btn-inverse", rel: :external  %>

	<br>
  <br>

  </div>
  
<% end %>

app/views/users/index.html.erb
<div class="container">
<h2>Listing users</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th class="headwidth">Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.phone %></td>
        <td class="headwidth"><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm:          'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.mobile.erb
<% provide(:title, 'Register') %>

<h2 style="font-family: Courier New; font-style:italic; margin:0; padding:0;">Register!</h2>

<br>

  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

   <div style="width:160px; height:90px;">

    
    <%= f.label :user_type %>
    <%= f.select :user_type, [["Driver", true],["Restaurant", false]] %>

    <br>
    <br>

  </div>

  <div class="span4" style="margin: 0 0 0 0px;">
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :phone %>
    <%= f.text_field :phone, placeholder: "8885551234" %>
 
    <%= f.label :address, "Restaurant Address", style: "display:none" %>
    <%= f.text_area :address, placeholder: "Full restaurant address", style: "display:none" %>
 
    <%= f.label :password %>
    <%= f.password_field :password, placeholder: "6 char min" %>

    <%= f.label :password_confirmation, "Confirm password" %>
    <%= f.password_field :password_confirmation %>

  <br>
  <br>
  
    <%= f.submit "Start!", class: "btn-large btn-inverse", "data-ajax" => "false" %>

  </div>
  
<% end %>

app/views/users/pickups.mobile.erb
<%= render "shared/javascript_headers" %>

<% provide(:title, 'Running Pickups') %>

<h3 style="font-family: Courier New; font-style:italic; margin-left:0; margin-top:20px; padding:0;">Running Pickups:</h3>

<div  id="map" style="position:absolute; width:95%; height:80%;"></div>


      <%= render 'shared/gmap_script' %>

app/views/users/running.html.erb
<% provide(:title, 'Running') %>

  <div  id="map" style="position:absolute; width:100%; height:100%;"></div>

      <%= render 'shared/gmap_script' %>



    

app/views/users/running.mobile.erb
<%= render "shared/javascript_headers" %>

<% provide(:title, 'Running') %>

<div  id="map" style="position:absolute; width:100%; height:100%;"></div>


      <%= render 'shared/gmap_script' %>

app/views/users/show.html.erb
<% provide(:title, 'User Info') %>
<div class="container">

  <h3> User Register: </h3>
  <br> 

  

<p><h4>
  <%= @user.name %>
</h4></p>

<p><h4>
  <%= @user.user_type ? 'Driver' : 'Restaurant' %>
</h4></p>

<p><h4>
  <%= @user.phone %>
</h4></p>

<p><h4>
  <%= @user.address %>
</h4></p>




<br>
<%= link_to 'Edit', edit_user_path(@user) %> 
</div>

app/views/users/show_run.html.erb
    <% provide(:title, 'Now Running') %>
    

   <div class="container">

    <h3> Running: </h3>

    <%= render 'shared/feed' %>
    

  </div>

    