config/routes.rb
Runnery::Application.routes.draw do

 resources :users
 resources :sessions, only: [:new, :create, :destroy]
 resources :orders, only: [:create,:destroy,:update]
 resources :locations, only: [:create,:destroy,:update]

 root 'static_pages#home'

 match '/running',  to: 'users#running',  via: 'get'
 match '/done',  to: 'users#done_today',  via: 'get'
 match '/all_done',  to: 'users#all_done',  via: 'get'
 match '/signup',  to: 'users#new',  via: 'get'
 match '/signin',  to: 'sessions#new',         via: 'get'
 match '/signout', to: 'sessions#destroy',     via: 'delete'
 match '/site_info', to: 'static_pages#site_info', via: 'get'
 match '/dropoffs_wait', to: 'static_pages#dropoffs_wait', via: 'get'
 match '/pickups_wait', to: 'static_pages#pickups_wait', via: 'get'
 match '/dropoffs',  to: 'users#dropoffs',  via: 'get'
 match '/pickups',  to: 'users#pickups',  via: 'get'
 match '/dropoffs_done',  to: 'users#dropoffs_done',  via: 'get'
 match '/pickups_done',  to: 'users#pickups_done',  via: 'get'

end

app/views/shared/_error_messages.mobile.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  	
    <%= render partial: 'shared/feed_item', collection: @feed_items %>

<% end %>

app/views/shared/_feed.mobile.erb
<% if @feed_items.any? %>
  	
    <%= render partial: 'shared/feed_item', collection: @feed_items %>

<% end %>

app/views/shared/_feed_item.html.erb
<div style="font-family: Courier New; background: rgba(172,228,252,.5)">
  <% if !feed_item.running %>
  <% if driver? %>

       <b>P: </b><%= feed_item.origin_address %>

       <br>

       <b>D: </b><%= feed_item.address %>

       <br>

  <% else %>

        <%= feed_item.phone %>

        <br>

        <%= feed_item.address %>

        <br>

  <% end %>
<% end %>

<% if feed_item.running %>
  <% if driver? %>

       <li class="dropdown">

        <a href="#" class="dropdown-toggle" 
            data-toggle="dropdown" style="color:black;">

            <b>P: </b><%= feed_item.origin_address %>

        </a>

          <ul class="dropdown-menu" style="font-family: Courier New">              

            <%= feed_item.origin_phone %>

          </ul>

       </li>         

  <% else %>

        <li class="dropdown">

          <a href="#" class="dropdown-toggle" 
            data-toggle="dropdown" style="color:black;">

            <%= feed_item.driver_name %>

          </a>

            <ul class="dropdown-menu" style="font-family: Courier New">              

            <%= feed_item.driver_phone %>

            </ul>

        </li>

  <% end %>

        <li class="dropdown">

          <a href="#" class="dropdown-toggle" 
             data-toggle="dropdown" style="color:black;">

                <% if driver? %>
                  <b>D:</b>
                <% end %>

                <%= feed_item.address %>

          </a>

            <ul class="dropdown-menu" style="font-family: Courier New">              

              <%= feed_item.phone %>

            </ul>

        </li>   

<% end %>




<column style="font-family: new courier">$</column>
<%= feed_item.surcharge %>

  <br>
    
<%= feed_item.pay_type ? 
    'Pay cash up-front' : 'Paid with card' %>

  <br>
    
<%= time_ago_in_words(feed_item.created_at) %> ago.

</div>

 <br>  

<% if !feed_item.running %>
  <% if driver? %>
    <% if current_user.driver_run.count >= 3 %>

      Please finish a run!

        <br>
        <br>

    <% else %>

      <%= form_for feed_item do |f| %>
     
        <%= f.hidden_field :driver_id, 
                          :value => current_user.id %>

        <%= f.submit "Run!",
              class: "btn-small btn-success", rel: :external %> 

      <% end %>

    <% end %>
  <% end %>
<% else %>
  <% if driver? && !feed_item.done %>
  
  <button id="pickup" class="btn-small btn-warning" style="text-color:black;">NOT PICKED UP!!!</button>
    
   <% if feed_item.paid_card %>

<box style="float:left; margin-right:50px">

      <li class="dropdown" id="done">
        
        <a href="#" class="btn btn-small 
                btn-inverse dropdown-menu-toggle" 
           data-toggle="dropdown" style="color:white; width:55px; height: 21px; padding:0; border:0;">
                
                Done!

        </a>

        <ul class="dropdown-menu" style="background-color: rgba(0,0,0,0); box-shadow:none;"> 

          <br>

          <%= form_for feed_item do |f| %>

            <%= f.hidden_field :receipt, :value => true %>
            
            <%= f.submit "Receipt", class: "btn btn-inverse", :style => 'opacity:1', rel: :external%>

          <% end %>

          <%= form_for feed_item do |f| %>
     
            <%= f.hidden_field :receipt, :value => false %>

            <%= f.submit "NO receipt", class: "btn btn-inverse", :style => 'opacity:1', rel: :external %> 

          <% end %>
                  
        </ul>
            
      </li>

    </box>

    <% else %>

<box style="float:left; margin-right:50px">

        <%= form_for feed_item do |f| %>

          <%= f.hidden_field :receipt, :value => false %>

          <%= f.submit "Done!", class: "btn-small btn-inverse", rel: :external %> 

        <% end %>

      </box>

    <% end %>

    <box>

      <%= form_for feed_item do |f| %>
     
        <%= f.hidden_field :driver_id, :value => nil %>

        <%= f.submit "Stop!", class: "btn-small btn-danger", rel: :external %> 

      <% end %>

    </box>

  <% end %>
<% end %>
<% if feed_item.done %>
  <% if driver? %>
    <% if feed_item.redeemed? %>
    <% else %>
    <% if feed_item.receipt? %>

      <%= form_for feed_item do |f| %>
     

        <%= f.hidden_field :redeemed, :value => true %>

        <%= f.submit "Receipt!", class: "btn-small btn-warning", rel: :external %> 

      <% end %>

    <% else %>

    <% end %>
    <% end %>
  <% end %>
  <br>
<% end %>

<% if !driver? && !feed_item.done%>
   
  <%= button_to "Cancel!", feed_item, class: "btn-danger",
                method: :delete, 
                data: { confirm: "Please inform the driver of this cancellation." },
                title: feed_item.user_id, rel: :external  %>

<% end %>

app/views/shared/_feed_item.mobile.erb
<div style="font-family: Courier New; background: rgba(172,228,252,.5)">
  <% if !feed_item.running %>
  <% if driver? %>

       <b>P: </b><%= feed_item.origin_address %>

       <br>

       <b>D: </b><%= feed_item.address %>

       <br>

  <% else %>

        <%= feed_item.phone %>

        <br>

        <%= feed_item.address %>

        <br>

  <% end %>
<% end %>

<% if feed_item.running %>
  <% if driver? %>

       <li class="dropdown">

        <a href="#" class="dropdown-toggle" 
            data-toggle="dropdown"style="color:black;">

            <b>P: </b><%= feed_item.origin_address %>

        </a>

          <ul class="dropdown-menu" style="font-family: Courier New">              

            <%= feed_item.origin_phone %>

          </ul>

       </li>         

  <% else %>

        <li class="dropdown">

          <a href="#" class="dropdown-toggle" 
            data-toggle="dropdown" style="color:black;">

            <%= feed_item.driver_name %>

          </a>

            <ul class="dropdown-menu" style="font-family: Courier New">              

            <%= feed_item.driver_phone %>

            </ul>

        </li>

  <% end %>

        <li class="dropdown">

          <a href="#" class="dropdown-toggle" 
             data-toggle="dropdown" style="color:black;">

                <% if driver? %>
                  <b>D:</b>
                <% end %>

                <%= feed_item.address %>

          </a>

            <ul class="dropdown-menu" style="font-family: Courier New">              

              <%= feed_item.phone %>

            </ul>

        </li>   

<% end %>




<column style="font-family: new courier">$</column>
<%= feed_item.surcharge %>

  <br>
    
<%= feed_item.pay_type ? 
    'Pay cash up-front' : 'Paid with card' %>

  <br>
    
<%= time_ago_in_words(feed_item.created_at) %> ago.

</div>

 <br>  

<% if !feed_item.running %>
  <% if driver? %>
    <% if current_user.driver_run.count >= 3 %>

      Please finish a run!

        <br>
        <br>

    <% else %>

      <%= form_for feed_item do |f| %>
     
        <%= f.hidden_field :driver_id, 
                          :value => current_user.id %>

        <%= f.submit "Run!",
              class: "btn-small btn-success", rel: :external %> 

      <% end %>

    <% end %>
  <% end %>
<% else %>
  <% if driver? && !feed_item.done %>
    <% if feed_item.paid_card %>

<box style="float:left; margin-right:50px">

      <li class="dropdown" id="done">
        
        <a href="#" class="btn btn-small 
                btn-inverse dropdown-menu-toggle" 
           data-toggle="dropdown" style="color:white; width:55px; height: 21px; padding:0; border:0;">
                
                Done!

        </a>

        <ul class="dropdown-menu" style="background-color: rgba(0,0,0,0); box-shadow:none;"> 

          <br>

          <%= form_for feed_item do |f| %>

            <%= f.hidden_field :receipt, :value => true %>
            
            <%= f.submit "Receipt", class: "btn btn-inverse", :style => 'opacity:1', rel: :external %>

          <% end %>

          <%= form_for feed_item do |f| %>
     
            <%= f.hidden_field :receipt, :value => false %>

            <%= f.submit "NO receipt", class: "btn btn-inverse", :style => 'opacity:1', rel: :external %> 

          <% end %>
                  
        </ul>
            
      </li>

    </box>

    <% else %>

<box style="float:left; margin-right:50px">

        <%= form_for feed_item do |f| %>

          <%= f.hidden_field :receipt, :value => false %>

          <%= f.submit "Done!", class: "btn-small btn-inverse", rel: :external %> 

        <% end %>

      </box>

    <% end %>

    <box>

      <%= form_for feed_item do |f| %>
     
        <%= f.hidden_field :driver_id, :value => nil %>

        <%= f.submit "Stop!", class: "btn-small btn-danger", rel: :external %> 

      <% end %>

    </box>

  <% end %>
<% end %>
<% if feed_item.done %>
  <% if driver? %>
    <% if feed_item.redeemed? %>
    <% else %>
    <% if feed_item.receipt? %>

      <%= form_for feed_item do |f| %>
     

        <%= f.hidden_field :redeemed, :value => true %>

        <%= f.submit "Receipt!", class: "btn-small btn-warning", rel: :external %> 

      <% end %>

    <% else %>

    <% end %>
    <% end %>
  <% end %>
  <br>
<% end %>

<% if !driver? && !feed_item.done%>
   
  <%= button_to "Cancel!", feed_item, class: "btn-danger",
                method: :delete, 
                data: { confirm: "Please inform the driver of this cancellation." },
                title: feed_item.user_id, rel: :external   %>

<% end %>





app/views/shared/_gmap_script.html.erb
<script type="text/javascript">
       
                
        handler = Gmaps.build('Google');
        handler.buildMap
    
    	({ provider: {}, internal: {id: 'map'}}, function(){
    	        
           markers = handler.addMarkers(<%=raw @hash.to_json %>);
           handler.bounds.extendWith(markers);
           handler.fitMapToBounds();
           
        });

        
</script>


app/views/shared/_gmap_script.mobile.erb
<script type="text/javascript">

    handler = Gmaps.build('Google');
    handler.buildMap
    
    	({ provider: {}, internal: {id: 'map'}}, function(){
   		   markers = handler.addMarkers(<%=raw @hash.to_json %>);
           handler.bounds.extendWith(markers);
           handler.fitMapToBounds();
        });

</script>

app/views/shared/_javascript_headers.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>

<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

app/views/shared/_javascript_headers.mobile.erb
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAppsdS-4b211KGHnVR7DYlHnP1J26NsyM&callback=initMap"
  type="text/javascript"></script>

app/views/shared/_order_form.html.erb
<%= form_for Order.new do |f| %>
  <div class="field">

    <%= f.label :address %>
    <%= f.text_area :address, placeholder: "Full delivery address" %>

    <%= f.label :phone %>
    <%= f.text_field :phone, placeholder: "8885551234" %>

    <%= f.label :surcharge %>
    <%= f.text_field :surcharge, value: "3.00" %>

    <%= f.label :pay_type %>
    <%= f.select :pay_type, [["Cash up-front", true],["Paid with Card", false]] %>

  </div>

  <br>
  
  <%= f.submit "Post!", class: "btn btn-large btn-inverse" %>
<% end %>

app/views/shared/_order_form.mobile.erb
<%= form_for Order.new do |f| %>
  <div class="field">

    <%= f.label :address %>
    <%= f.text_area :address, placeholder: "Full delivery address" %>

    <%= f.label :phone %>
    <%= f.text_field :phone, placeholder: "8885551234" %>

    <%= f.label :surcharge %>
    <%= f.text_field :surcharge, value: "3.00" %>

    <%= f.label :pay_type %>
    <%= f.select :pay_type, [["Cash up-front", true],["Paid with Card", false]] %>

  </div>

  <br>
  
  <%= f.submit "Post!", class: "btn btn-large btn-inverse", rel: :external %>
<% end %>

app/views/shared/_sign_in.mobile.erb
<br>

<div class="span4" style="background: rgba(172,228,252,.4); margin:25px 0 0 0px;box-shadow: 10px 10px 5px #434343;margin:0 0 0 0px;">

<p style="margin: 10px 0 0 10px"> Welcome to</p>
  	  <h1 style= "padding-top:0px;margin: 0 0 0 10px">Runnery!!!</h1>
  	  <h5 style="padding-left:20px">
  	     Shared restaurant delivery
  	  </h5>

<br>

<div style="margin:0px 10px 10px 10px">

	<%= form_for(:session, url: sessions_path) do |f| %>

  	<%= f.label :phone %>
  	<%= f.phone_field :phone, placeholder: "8885551234" %>

  	<%= f.label :password %>
  	<%= f.password_field :password %>

    <br>
    <br>

  	<%= f.submit "Sign in!", class: "btn btn-large btn-inverse", rel: :external %>

		<% end %>

    <%= link_to "Register!", signup_path, class: "btn", rel: :external, style: "color:black" %>

	</div>
	</div>
 </div>

app/views/shared/_stats.html.erb
<% if !driver? %>
<div class="stats" style="margin-left:20px">
  <a href="/" style="color:black;", rel="external" >
    <div id="waiting" class="stat">
      <%= current_user.restaurant_wait.count %>
    </div>
    Waiting
  </a>
  <a href="<%= running_path %>" style="color:black;", rel="external">
    <div id="running" class="stat">
      <%= current_user.restaurant_run.count %>
    </div>
    Running
  </a>
  <a href="<%= done_path %>" style="color:black;", rel="external">
    <div id="done" class="stat">
      <%= current_user.restaurant_done.count %>
    </div>
    Done
  </a>
</div>

<% else %>

<div class="stats" style="margin-left:20px">
  <a href="/" style="color:black;", rel="external">
    <div id="waiting" class="stat" >
      <%= current_user.driver_wait.count %>
    </div>
    Waiting
  </a>
  <a href="<%= running_path %>" style="color:black;", rel="external">
    <div id="running" class="stat">
      <%= current_user.driver_run.count %>
    </div>
    Running
  </a>
  <a href="<%= done_path %>"  style="color:black;", rel="external">
    <div id="done" class="stat">
      <%= current_user.driver_done.count %>
    </div>
    Done
  </a>
</div>

<% end %>

app/views/shared/_user_info.html.erb
<h2>
  <%= current_user.name %>
</h2>