config/routes.rb
Runnery::Application.routes.draw do

 resources :users
 resources :sessions, only: [:new, :create, :destroy]
 resources :orders, only: [:create,:destroy,:update]
 resources :locations, only: [:create,:destroy,:update]

 root 'static_pages#home'

 match '/running',  to: 'users#running',  via: 'get'
 match '/done',  to: 'users#done_today',  via: 'get'
 match '/all_done',  to: 'users#all_done',  via: 'get'
 match '/signup',  to: 'users#new',  via: 'get'
 match '/signin',  to: 'sessions#new',         via: 'get'
 match '/signout', to: 'sessions#destroy',     via: 'delete'
 match '/site_info', to: 'static_pages#site_info', via: 'get'
 match '/dropoffs_wait', to: 'static_pages#dropoffs_wait', via: 'get'
 match '/pickups_wait', to: 'static_pages#pickups_wait', via: 'get'
 match '/dropoffs',  to: 'users#dropoffs',  via: 'get'
 match '/pickups',  to: 'users#pickups',  via: 'get'
 match '/dropoffs_done',  to: 'users#dropoffs_done',  via: 'get'
 match '/pickups_done',  to: 'users#pickups_done',  via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom" 
  style="background-color: black">
 <nav>
  <div class="container">
    <ul class="pull-left" style="margin: 0 0 0 0px">

      <% if signed_in? %>
      
         <li style="margin: 0 0 0 0px;">
        <%= link_to "Site Info", site_info_path, style: "color:white" %>
      </li>    

        <li style="color:white;"> | </li>

        <li><%= link_to "Edit Register", edit_user_path(current_user), style: "color:white" %></li>
        
        <li style="color:white;"> | </li>

      <% end %>

       <li style="color:white;">
          <a href="/?mobile=1", style="color:white;", rel="external">Mobile</a>
      </li>

      <% if signed_in? %>

        <li style="color:white;"> | </li>

        <li><%= link_to "Sign out", signout_path, method: "delete", style: "color:white" %></li>

      <% end %>
    </ul>
  </div>
 </nav>
</footer>

app/views/layouts/_footer.mobile.erb
<footer class="navbar navbar-fixed-bottom" 
  style="background-color: black;">
  
  <center class="wrapper">

    <div class="wrapper" style="margin-bottom:5px;">

    <col style="margin: 0 0 0 0px;">
      <%= link_to "Site Info", site_info_path, style: "color:white;font-size:12px;", rel: :external %>
    </col>    

      <span style="color:white;font-size:12px;">|</span>

      <col>
        <a href="/?mobile=0", style="color:white;font-size:12px;", rel="external">Desktop</a>
      </col>

      <% if signed_in? %>

        <span style="color:white;font-size:12px;">|</span>

        <col><a href="<%= signout_path %>"  data-method="delete", style="color:white;font-size:12px;", data-ajax="false" %>Sign Out</a></col>

      <% end %>
    </div>
    </center>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="navbar-inner">
<div class="container">
<%= link_to image_tag("hat.png", alt: "Delivery"), root_path, id: "image", 
            style: "margin-left:48%; width:35px; height:30px; margin-top:10px; padding:0;",rel: :external %>
</div>
</div>
</header>

app/views/layouts/_header.mobile.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner" style="height:20px;">

    	<% if signed_in? %>

	    	<center class="wrapper" style="margin-top:10px;">

	    		

					  <%= link_to "Waiting", root_path, style: "color:white;font-size:18px;", rel: :external %> 
					  <span style="with:auto; color:white;font-size:18px;">|
					  </span>
					  <%= link_to "Running", running_path, style: "color:white;font-size:18px;", rel: :external%> 
					  <span style=" color:white;font-size:18px;">|
					  </span>
					  <%= link_to "Done", done_path, style: "color:white; font-size:18px;", rel: :external %>

					</center>
			    
			  	

			

		<% else %>


				<%= link_to image_tag("hat.png", alt: "Delivery"), root_path, id: "image", style: "margin-left:48%; width:35px; height:30px; margin-top:10px; padding:0;", rel: :external %>


		<% end %>
	</div>
</header>

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <! [endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
	<head>
		
  		<title><%= full_title(yield(:title)) %></title>
  		<meta name="viewport" content="width=device-width, initial-scale=1">
  	  	<%= stylesheet_link_tag "application" %>
  	  	<%= stylesheet_link_tag 'mobile' if mobile_device? %>
  	  	<%= javascript_include_tag "application" %>
 	  	<%= csrf_meta_tags %>
  	  	<%= render 'layouts/shim' %>
  	  	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAppsdS-4b211KGHnVR7DYlHnP1J26NsyM&callback=initMap"
  type="text/javascript"></script>
  	  	
  	  </head>

	<body style="position:absolute; width:100%; height:100%;">
				<div style="background-color:transparent;text-shadow:none;font-size:13px;" data-role="page">

		<div data-role="header">
		<%= render 'layouts/header' %>
		
		<br>
		<br>
		</div>
		
			<%= yield %>
			
			<% flash.each do |key, value| %>

        		<%= content_tag(:div, value, class: "alert alert-#{key}") %>
	
			<%end%>
				
				<% if signed_in? %>
					<% if !driver? %>
				
						<div style="margin-left:90px;margin-top:15px;position:relative;width:240px;
									background: rgba(172,228,252,.5); box-shadow: 10px 10px 5px #888888;z-index:1"> 
				
					<div style="margin:10px 10px 10px 10px">
						<h3>Deliveries:</h3>
						

        			<%= render 'shared/stats' %>
        			
        			
        			 <li class="dropdown">
           				 <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             				 <h4 style="color:black;">Post Delivery:</h4>
           				 </a>
				            <ul class="dropdown-menu" style="width:350px; background: rgba(172,228,252,.5); box-shadow: 10px 10px 5px #888888;">
				              <br><li style="margin:10px 10px 10px 10px"><%= render 'shared/order_form'%></li>
				            </ul>
			         </li>
					</div>
        			</div>
        			
        			<% else %>
        			
        			
<script type="text/javascript">

   $(document).ready(function(){ navigator.geolocation.getCurrentPosition(

        function(pos){
          $("#latitude").val(pos.coords.latitude);
          $("#longitude").val(pos.coords.longitude);

                           
  });
 });   

</script>

        			
        				<div style="margin-left:90px;margin-top:15px;position:relative;width:240px;
									background: rgba(172,228,252,.5); box-shadow: 10px 10px 5px #888888;z-index:1;"> 
				
					<div style="margin:10px 10px 10px 10px">
						<h4 class="span2">Deliveries:</h4>
        				
        				

       <%= form_for Location.new do |f| %>

        
          <%= f.hidden_field :lat, :id => "latitude" %>
       
          <%= f.hidden_field :lng, :id => "longitude" %>

          <%= f.submit "Locate", 
                class: "btn btn-info btn-small", style: "margin-top:5px", :id => "autolocate", :rel => "external" %>
                    
        <% end %>

     
        			<%= render 'shared/stats' %>
        			
        			
        		
    
      			</div>
      			</div>
      					<%end%>
      				<%end%>

	<div data-role="footer">
		<script src="scroll.js"></script>
		<%= render 'layouts/footer' %>
	</div>
	
	
	</div>
	
		<div style="position:absolute;bottom:0;width:100%;">
	
		<%= debug(params) if Rails.env.development? %>
		
		</div>
	
	</body>
	
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html>

  <head>

    <title><%= full_title(yield(:title)) %></title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    

   <%= stylesheet_link_tag    "application" %>
   <%= javascript_include_tag "application" %>

    <script src="//maps.google.com/maps/api/js?v=3.14&amp;sensor=false&amp;libraries=geometry" type="text/javascript">
        </script>

    <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.1.2/src/markerclusterer_packed.js" type="text/javascript">
    </script>

      
      <%= csrf_meta_tags %>

      <%= yield(:head) %>

  </head>
  <body style="position:absolute; width:100%; height:100%;">
		<div style="text-shadow:none;font-size:13px;" data-role="page">

		<div data-role="header">
		<%= render 'layouts/header' %>
		
		<br>
		<br>
		</div>
		
	
			<%= yield %>

			<% flash.each do |key, value| %>

        		<%= content_tag(:div, value, 
        			class: "alert alert-#{key}")%>
	
			<%end%>
				
				<% if signed_in? %>
					<% if !driver? %>
			
        			 <li class="dropdown">
           				 <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             				 <h4 style="margin:10px 10px 10px 10px; background: rgba(172,228,252,.9);box-shadow: 10px 10px 5px #888888;
             				 margin-left:90px;margin-top:30px; width:150px;position:relative; z-index:1; color:black;">Post Delivery:</h4>
           				 </a>
				            <ul class="dropdown-menu" style="left:100px;width:350px;background: rgba(172,228,252,.9);box-shadow: 10px 10px 5px #888888">
				              <br><li style="margin:10px 10px 10px 10px"><%= render 'shared/order_form'%></li>
				            </ul>
			         </li>
        			
        			<% else %>
        			
        			
<script type="text/javascript">

   $(document).ready(function(){ navigator.geolocation.getCurrentPosition(

        function(pos){
          $("#latitude").val(pos.coords.latitude);
          $("#longitude").val(pos.coords.longitude);

                           
  });
 });   

</script>

       <%= form_for Location.new do |f| %>

        
          <%= f.hidden_field :lat, :id => "latitude" %>
       
          <%= f.hidden_field :lng, :id => "longitude" %>

          <%= f.submit "Locate", 
                class: "btn btn-info", style: "position:relative;z-index:1;margin-left:90px;margin-top:25px", :id => "autolocate", :rel => "external" %>
                    
        <% end %>
        			
        			
      					<%end%>
      				<%end%>

	<div date-role="footer">
		<%= render 'layouts/footer' %>
	</div>
	
		<%= debug(params) if Rails.env.development? %>

	</div>
	
	</body>
</html>